//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace пр5.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NakladnayaProdukt
    {
        public int IDNakladnoi { get; set; }
        public int IDProdukta { get; set; }
        public int Kolichestvo { get; set; }
        public decimal Stoimost { get; set; }
    
        public virtual Nakladnaya Nakladnaya { get; set; }
        public virtual Product Product { get; set; }
    }
}
