//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace пр5.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nakladnaya
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Nakladnaya()
        {
            this.NakladnayaProdukt = new HashSet<NakladnayaProdukt>();
        }
    
        public int IDNakladnoi { get; set; }
        public int IDPostavshika { get; set; }
        public int IDSotrudnika { get; set; }
        public System.DateTime Data { get; set; }
        public decimal Stoimost { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NakladnayaProdukt> NakladnayaProdukt { get; set; }
        public virtual Postavshik Postavshik { get; set; }
    }
}
