//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace пр5.models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NapitkiEntities : DbContext
    {
        public NapitkiEntities()
            : base("name=NapitkiEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Dolznosti> Dolznosti { get; set; }
        public virtual DbSet<Klienti> Klienti { get; set; }
        public virtual DbSet<Nakladnaya> Nakladnaya { get; set; }
        public virtual DbSet<NakladnayaProdukt> NakladnayaProdukt { get; set; }
        public virtual DbSet<Postavshik> Postavshik { get; set; }
        public virtual DbSet<Product> Product { get; set; }
        public virtual DbSet<Produkcia> Produkcia { get; set; }
        public virtual DbSet<Sotrudnik> Sotrudnik { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Zakazi> Zakazi { get; set; }
    }
}
