//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace пр5.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sotrudnik
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Familia { get; set; }
        public string Otchestvo { get; set; }
        public int IDDolznost { get; set; }
        public string Email { get; set; }
        public string PasportSeries { get; set; }
        public string PasportNumber { get; set; }
    
        public virtual Dolznosti Dolznosti { get; set; }
        public virtual Users Users { get; set; }
    }
}
