//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace пр5.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zakazi
    {
        public int ID { get; set; }
        public int IDKlient { get; set; }
        public string Naimenovanie { get; set; }
        public int Kolichestvo { get; set; }
        public decimal Stoimost { get; set; }
        public string Oplata { get; set; }
    
        public virtual Klienti Klienti { get; set; }
        public virtual Produkcia Produkcia { get; set; }
    }
}
